improve testing suite, implement new tests
Boosted-Finance/smart-contracts pull request #3
Opened 2020-09-10 01:37 UTC by hems

Here is a Draft PR I created while testing the library and learning more about how it works, please let me know if I'm missing something, I'm happy to improve / revert some of the changes if necessary.

---

UPDATES:

  - Fix title of test "should revert staking at a pool with amount exceeding token cap", which actually expected the test to `NOT` revert

  - Changes REWARD_AMOUNT to 6048 in order to make numbers round during tests

  - Do not transfer wETH to Alice as Alince does not use wETH

  - Initialize tokens and pool before each test as opposed to once at the start and updates all tests accordingly, therefore:
      - makes every test into a independent test
      - improve clarity in each of the tests
      - allow tests to be re-ordered freely
      - allow easily addding or removing tests

  - Adds Bob account
      - allows tests with more than one participant in the pool
      - implement test where bob takes 25% of the pool

  - Remove duplicated tests on wBTC pool
      - some of the tests for wBTC tested exactly the same piece of code
      on two identical contracts which i ( possibly wrongly ) assumed  
      to be unecessary

2020-09-13 00:10 UTC, JoaquinLiHua requested changes
Small change requested =)

2020-09-13 00:10 UTC, JoaquinLiHua commented on .solcover.js
> +};
Kindly add a newline after this!

2020-09-13 00:13 UTC, JoaquinLiHua commented
Hello, thanks for submitting the PR!

If you'd like to work on tests for the new governance and treasury contracts, or on developing the smart contracts in general, send a PM on discord to either Boosted Barry or BarryNaut =)

2020-09-18 05:46 UTC, JoaquinLiHua commented
@hems when you have fixed the minor errors, happy to merge and close this PR

2020-09-18 19:26 UTC, hems commented on .solcover.js
> +};
@JoaquinLiHua added!

2020-09-18 19:27 UTC, hems commented
> @hems when you have fixed the minor errors, happy to merge and close this PR

just added the new line! 🚀

2021-05-15 02:03 UTC, closed without merging