Add TreasuryV3
Boosted-Finance/smart-contracts pull request #7
Opened 2021-03-26 01:19 UTC by professor-boost

2021-03-30 03:50 UTC, JoaquinLiHua requested changes
Left some comments

2021-03-30 03:50 UTC, JoaquinLiHua commented on contracts/TreasuryV3.sol
> +        return token.balanceOf(address(this)).sub(ecoFundAmts[address(token)]);
remove ```.sub(ecoFundAmts[address(token)])```

2021-03-30 03:50 UTC, JoaquinLiHua commented on contracts/TreasuryV3.sol
> +        require(balanceOf(coin) >= amount, "insufficient funds");
can remove this require statement, safeTransfer should handle it

2021-03-30 03:50 UTC, JoaquinLiHua commented on contracts/TreasuryV3.sol
> +        coin.safeTransfer(withdrawAddress, amount);
refactor to ```IERC20(token).safeTransfer(withdrawAddress, amount)```

2021-03-30 03:50 UTC, JoaquinLiHua commented on contracts/TreasuryV3.sol
> +        require(routeDetails[0] != address(nativeToken), "src can't be boost");
remove, should allow for the src to be the ```BoostToken```

2021-03-30 03:50 UTC, JoaquinLiHua commented on contracts/TreasuryV3.sol
> +        require(routeDetails[routeDetails.length - 1] == address(nativeToken), "dest not defaultToken");
“dest cannot be nativeToken”

2021-03-30 03:50 UTC, JoaquinLiHua commented on contracts/TreasuryV3.sol
> +            srcToken.safeApprove(address(swapRouter), 0);
should not need to safeApprove twice

2021-04-08 16:26 UTC, professor-boost commented on contracts/TreasuryV3.sol
> +    function fundOrbitStation(uint256 amount) external onlyGov {
Potentially needs to call `notifyRewards` or update rewards on OrbitStation when Orbit proceeds sent to staking contract

2021-04-20 14:18 UTC, merged